import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import HeroUiThemeProvider from "@/components/providers/HeroUiThemeProvider";
import Footer from "@/components/Footer";
import { Toast } from "@heroui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <HeroUiThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Navbar></Navbar>
          <main className="flex-1">{children}</main>
          <Footer></Footer>
        </HeroUiThemeProvider>
        <Toast.Provider />
      </body>
    </html>
  );
}
